services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/app/app
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    profiles: [keycloak]
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    command: start-dev --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./app/hackplate/plates/auth_plates/keycloak/settings.json:/opt/keycloak/data/import/realm.json

volumes:
  keycloak_data:
